const router = require("express").Router();
const ctrl   = require("../controllers/cuotas.controller");
router.get("/pendientes",            ctrl.getPendientes);
router.get("/vencidas",              ctrl.getVencidas);
router.get("/venta/:idVenta",        ctrl.getByVenta);
router.get("/:id/fracciones",        ctrl.getFracciones);
router.post("/:id/fracciones",       ctrl.setFracciones);
router.delete("/:id/fracciones",     ctrl.deleteFracciones);
router.post("/",                     ctrl.create);
router.patch("/:id/estado",          ctrl.updateEstado);
router.patch("/:id/valores",         ctrl.updateValores);
module.exports = router;
