const router = require("express").Router();
const ctrl   = require("../controllers/facturas.controller");
router.get("/mis-facturas",            ctrl.getMisFacturas);
router.get("/cuotas-sin-factura",      ctrl.getCuotasSinFactura);
router.get("/solicitudes",             ctrl.getSolicitudes);
router.post("/generar-pendientes",     ctrl.generarPendientes);
router.post("/solicitar",              ctrl.solicitarFactura);
router.patch("/solicitudes/:id",       ctrl.resolverSolicitud);
router.get("/",             ctrl.getAll);
router.post("/",            ctrl.create);
router.patch("/:id/anular", ctrl.anular);
module.exports = router;
