require("dotenv").config();
const express     = require("express");
const cors        = require("cors");
const compression = require("compression");
const path        = require("path");
const fs          = require("fs");

const app  = express();
const PORT = process.env.PORT || 3000;

const IS_PROD = process.env.NODE_ENV === "production";

// Behind a TLS-terminating proxy (PaaS/Cloudflare/Nginx): trust X-Forwarded-* so req.secure and
// the HTTPS redirect below reflect the client's real protocol instead of the internal hop.
app.set("trust proxy", 1);

// Closed CORS allowlist. The SPA is same-origin (served by this same server, Bearer-token auth),
// so only the public app origin and local dev need cross-origin access.
const APP_URL = process.env.APP_URL || "https://sgi.somoselcondor.com";
const ALLOWED_ORIGINS = [
  APP_URL,
  `http://localhost:${PORT}`,
  `http://127.0.0.1:${PORT}`,
];

// Content-Security-Policy scoped to what the frontend actually loads: Google Fonts, unpkg (lucide
// icons, Leaflet + Leaflet-Geoman for the interactive lotes map), gstatic/google (Firebase Auth SDK
// + Google sign-in popup) and remote images (Cloudinary uploads, Google avatars, map tiles).
// 'unsafe-inline' is required by the inline theme/init scripts and the inline event handlers
// generated by the vanilla SPA.
// In dev the livereload client loads a script and opens a WebSocket from localhost:35729; allow it
// there so auto-reload keeps working without weakening the production policy.
const DEV_SCRIPT  = IS_PROD ? "" : " http://localhost:35729";
const DEV_CONNECT = IS_PROD ? "" : " ws://localhost:35729 http://localhost:35729";
const CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'self'",
  "img-src 'self' data: https:",
  "font-src 'self' https://fonts.gstatic.com",
  // unpkg.com also hosts leaflet.css + leaflet-geoman.css for the interactive lotes map (MAP-01/02/03).
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com",
  // jsdelivr/cdnjs host the lazy-loaded export libs (jspdf, exceljs, chart.js, html2pdf)
  // used by lib-loader.js and the printable comprobantes (which inherit this CSP).
  `script-src 'self' 'unsafe-inline' https://www.gstatic.com https://unpkg.com https://apis.google.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com${DEV_SCRIPT}`,
  // api.pwnedpasswords.com: k-anonymity password-breach check on registration/reset (SEG-06).
  `connect-src 'self' https://*.googleapis.com https://*.firebaseapp.com https://api.pwnedpasswords.com${DEV_CONNECT}`,
  "frame-src 'self' https://*.firebaseapp.com https://accounts.google.com https://apis.google.com",
].join("; ");

// In production serve the built, hashed index.prod.html (falls back to the dev index if the build
// hasn't run). Dev always serves the loose-script index.html, so livereload needs no build step.
const PROD_INDEX = path.join(__dirname, "..", "public", "index.prod.html");
const DEV_INDEX  = path.join(__dirname, "..", "public", "index.html");
const APP_INDEX  = IS_PROD && fs.existsSync(PROD_INDEX) ? PROD_INDEX : DEV_INDEX;

const { verificarToken }   = require('./middlewares/auth.middleware');
const { verificarPermiso } = require('./middlewares/permisos.middleware');


app.use(cors({
  origin(origin, cb) {
    // No Origin header = same-origin or non-browser client (curl, server-to-server): allow.
    if (!origin || ALLOWED_ORIGINS.includes(origin)) return cb(null, true);
    cb(null, false);
  },
}));
app.use(compression());
app.use(express.json());

// Force HTTPS in production and advertise HSTS only over secure connections. Skipped in dev so
// plain-HTTP localhost keeps working.
app.use((req, res, next) => {
  if (IS_PROD) {
    if (!req.secure) {
      return res.redirect(301, `https://${req.headers.host}${req.originalUrl}`);
    }
    res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  }
  next();
});

// Baseline security headers. SAMEORIGIN still allows the same-origin login iframe used by the
// public landing, while blocking external framing (clickjacking).
app.use((req, res, next) => {
  res.setHeader('X-Frame-Options', 'SAMEORIGIN');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
  res.setHeader('Content-Security-Policy', CSP);
  next();
});

if (!IS_PROD) {
  const livereload        = require('livereload');
  const connectLivereload = require('connect-livereload');

  const lrServer = livereload.createServer();
  lrServer.watch(path.join(__dirname, '..', 'public'));

  app.use(connectLivereload());
}

// Redirect *.html to extensionless clean URLs (301 for SEO canonical)
app.use((req, res, next) => {
  if (req.method === 'GET' && req.path.endsWith('.html')) {
    let clean = req.path.slice(0, -'.html'.length);
    if (clean === '/index') clean = '/';
    return res.redirect(301, clean + req.originalUrl.slice(req.path.length));
  }
  next();
});

// Public landing lives at the bare root (sgi.somoselcondor.com). The authenticated app is
// served by the SPA wildcard at any other path (login redirects to /app after sign-in).
// The previous /proyectos URL 301s to the root to keep a single canonical landing.
app.get('/proyectos', (req, res) => res.redirect(301, '/'));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, "..", "public", "proyectos.html")));

// Hashed, immutable bundles built into public/dist by build.mjs. Safe to long-cache because the
// ?v=<hash> query changes whenever the bundle content changes.
app.use('/dist', express.static(path.join(__dirname, "..", "public", "dist"), {
  immutable: true,
  maxAge: '1y',
}));

app.use(express.static(path.join(__dirname, "..", "public"), { extensions: ['html'] }));

// Serve favicon.ico without a token to avoid a 401 on the browser's automatic request.
app.get('/favicon.ico', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'public', 'src', 'img', 'favicon.svg'));
});

app.use('/api/v1/auth', require('./routes/auth.routes'));

// Public showcase endpoints — no token required (must stay before verificarToken below)
app.use('/api/v1/public', require('./routes/public.routes'));

app.get('/api/v1/firebase-config', (req, res) => {
  res.json({
    apiKey:            process.env.FIREBASE_API_KEY,
    authDomain:        process.env.FIREBASE_AUTH_DOMAIN,
    projectId:         process.env.FIREBASE_PROJECT_ID,
    storageBucket:     process.env.FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
    appId:             process.env.FIREBASE_APP_ID,
    measurementId:     process.env.FIREBASE_MEASUREMENT_ID,
  });
});

// EventSource cannot send an Authorization header: the live stream (REQ-07)
// receives the same Firebase ID token via ?token= and it is mapped into the
// header here so the normal auth middleware validates it.
app.use('/api/v1/requerimientos/stream', (req, _res, next) => {
  if (req.query.token && !req.headers.authorization) {
    req.headers.authorization = `Bearer ${req.query.token}`;
  }
  next();
});

app.use('/api/v1', verificarToken, verificarPermiso);

app.use('/api/v1/proyectos',      require('./routes/proyectos.routes'));
app.use('/api/v1/lotes',          require('./routes/lotes.routes'));
app.use('/api/v1/compradores',    require('./routes/compradores.routes'));
app.use('/api/v1/ventas',         require('./routes/ventas.routes'));
app.use('/api/v1/cuotas',         require('./routes/cuotas.routes'));
app.use('/api/v1/pagos',          require('./routes/pagos.routes'));
app.use('/api/v1/comisionistas',  require('./routes/comisionistas.routes'));
app.use('/api/v1/facturas',       require('./routes/facturas.routes'));
app.use('/api/v1/recibos',        require('./routes/recibos.routes'));
app.use('/api/v1/reportes',       require('./routes/reportes.routes'));
app.use('/api/v1/usuarios',       require('./routes/usuarios.routes'));
app.use('/api/v1/roles',          require('./routes/roles.routes'));
app.use('/api/v1/uploads',            require('./routes/uploads.routes'));
app.use('/api/v1/bank-transactions',  require('./routes/bank_transactions.routes'));
app.use('/api/v1/juridico',       require('./routes/juridico.routes'));
app.use('/api/v1/gastos',         require('./routes/gastos.routes'));
app.use('/api/v1/recepciones',    require('./routes/recepciones.routes'));
app.use('/api/v1/requerimientos', require('./routes/requerimientos.routes'));
app.use('/api/v1/notificaciones', require('./routes/notificaciones.routes'));
app.use('/api/v1/inventario',     require('./routes/inventario.routes'));
app.use('/api/v1/config',         require('./routes/config.routes'));
app.use('/api/v1/respaldos',      require('./routes/respaldos.routes'));
app.use('/api/v1/empresas-aliadas', require('./routes/empresas_aliadas.routes'));

// SPA wildcard: any other path serves the app shell; auth happens client-side
// and every /api/v1 call is validated by the middlewares above.
app.get("*", (req, res) => {
  res.sendFile(APP_INDEX);
});

const { actualizarMora } = require('./services/mora.service');

app.listen(PORT, () => {
  console.log(`SGI corriendo en http://localhost:${PORT}`);
  actualizarMora().catch(err => console.error('[mora] startup error:', err.message));
});

// Run mora sync every 24 h
setInterval(
  () => actualizarMora().catch(err => console.error('[mora] interval error:', err.message)),
  24 * 60 * 60 * 1000
);

// Daily housekeeping: drop read notifications older than 60 days
const { limpiarAntiguas } = require('./services/notificaciones.service');
setInterval(
  () => limpiarAntiguas(60).catch(err => console.error('[notificaciones] cleanup error:', err.message)),
  24 * 60 * 60 * 1000
);

// Daily housekeeping: drop expired/consumed 2FA challenges older than 2 days
const { limpiarExpirados: limpiarExpirados2FA } = require('./services/two-factor.service');
setInterval(
  () => limpiarExpirados2FA().catch(err => console.error('[2fa] cleanup error:', err.message)),
  24 * 60 * 60 * 1000
);

// Daily: force a fresh login roughly every 30 days per user (all roles), staggered.
const { revocarSesionesVencidas } = require('./services/session-revocation.service');
setInterval(
  () => revocarSesionesVencidas().catch(err => console.error('[sesion] revocacion error:', err.message)),
  24 * 60 * 60 * 1000
);

